# Generated by Django 2.2.1 on 2019-05-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HearingDate',
        ),
    ]
