# Generated by Django 2.2 on 2019-05-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalReview',
            fields=[
                ('type', models.CharField(choices=[('ENV_CEQA', 'Other CEQA Guidelines Section'), ('ENV_COMMUNITY_PLAN_DET', 'Community Plan-Determination'), ('ENV_COMMUNITY_PLAN_EXEMPT', 'Community Plan-Exemption/Exclusion'), ('ENV_COMMUNITY_PLAN_STUDY', 'Community Plan-Initial Study/Environmental Evaluation'), ('ENV_EIR_ADDENDUM', 'EIR Addendum'), ('ENV_EIR', 'Environmental Impact Report'), ('ENV_EIR_SUPPLEMENTAL', 'EIR Supplemental'), ('ENV_EXEMPT_CERT', 'Categorical Exemption-Certificate'), ('ENV_EXEMPT_CLASS_32', 'Categorical Exemption-Class 32'), ('ENV_EXEMPT_HISTORIC_IMPACT', 'Categorical Exemption-Determination of Historic Resource Impact'), ('ENV_EXEMPT_HISTORIC_RESOURCE', 'Categorical Exemption-Determination of Historic Resource'), ('ENV_EXEMPT_STAMP', 'Categorical Exemption-Stamp'), ('ENV_GEN_RULE_EXCLUSION', 'General Rule Exclusion'), ('ENV_INIT_STUDY_EIR', 'Initial Study-Environmental Impact Report'), ('ENV_INIT_STUDY', 'Initial Study'), ('ENV_INIT_STUDY_NEGATIVE_DEC', 'Initial Study-Negative Declaration'), ('ENV_NEG_DEC_ADDENDUM', 'Negative Declaration Addendum'), ('ENV_NOTE', 'Note to File'), ('ENV_PUBLIC_PROJECT_EXEMPT', 'Public Project Exemption'), ('ENV_REVIEW_EXEMPTION_OTHER_AGENCY', 'Review-Exemption Prepared by Another Agency'), ('ENV_TRANSPO_REVIEW', 'Transportation Review-Abbreviated')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MCDReferral',
            fields=[
                ('type', models.CharField(choices=[('MCD_BAR', 'Bar'), ('MCD_GEN_SPEC_GROCERY', 'General/Specialty Grocery'), ('MCD_LIMITED_RESTAURANT', 'Limited-Restaurant'), ('MCD_MASSAGE', 'Massage Establishment'), ('MCD_MEDICAL_CANNABIS', 'Medical Cannabis Dispensary'), ('MCD_RESTAURANT', 'Restaurant'), ('MCD_TOBACCO', 'Tobacco Paraphernalia')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='str_id',
            new_name='planner_id',
        ),
        migrations.RemoveField(
            model_name='projectdescription',
            name='env_type',
        ),
        migrations.RemoveField(
            model_name='projectdescription',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projectdescription',
            name='mcd_type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='dwelling_type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='land_use',
        ),
        migrations.AddField(
            model_name='dwellingtype',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppts.Record'),
        ),
        migrations.AddField(
            model_name='landuse',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppts.Record'),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppts.Record'),
        ),
        migrations.AddField(
            model_name='recordtype',
            name='category',
            field=models.CharField(default='', help_text='3-letter acronym for the record type (e.g. PRJ, PRL, ENV).  There are 63 types.', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='shape_area',
            field=models.DecimalField(decimal_places=15, help_text='Area of polygon', max_digits=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='shape_length',
            field=models.DecimalField(decimal_places=8, help_text='Perimeter of polygon', max_digits=15),
        ),
        migrations.AlterField(
            model_name='projectdescription',
            name='type',
            field=models.CharField(choices=[('ADDITIONS', 'Additions'), ('ADU', 'Accessory Dwelling Unit'), ('AFFORDABLE_UNITS', '100% Affordable Housing'), ('CHANGE_OF_USE', 'Change of Use'), ('DEMOLITION', 'Demolition'), ('ENVIRONMENTAL_REVIEW_TYPE', 'Environmental Review'), ('FACADE_ALT', 'Facade Alterations'), ('FINANCIAL', 'Financial Services'), ('FORMULA_RETAIL', 'Formula Retail'), ('INCLUSIONARY', 'Inclusionary Housing Required'), ('LEG_ZONE_CHANGE', 'Legislative/Zoning Change'), ('LOT_LINE_ADJUST', 'Lot Line Adjustment-Subdivision'), ('MASSAGE', 'Massage Establishment'), ('MCD', 'Medical Cannabis Dispensary'), ('MCD_REFERRAL', 'Public Health Review - MCD'), ('NEW_CONSTRUCTION', 'New Construction'), ('OTHER_NON_RES', 'Non-Residential Use Type - Other'), ('OTHER_PRJ_DESC', 'Other'), ('ROW_IMPROVE', 'ROW Improvements'), ('SENIOR', 'Senior Housing'), ('SPECIAL_NEEDS', 'Special Needs Housing'), ('STATE_DENSITY_BONUS', 'State Density Bonus'), ('STUDENT', 'Student Housing'), ('TOBACCO', 'Tobacco Paraphernalia Est')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='name',
            field=models.CharField(help_text='Expansion of the 3-letter acronym (e.g. PRJ, PRL, ENV). There are 63 types.', max_length=100),
        ),
        migrations.CreateModel(
            name='HearingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOS_1ST_READ', 'Full Board Hearing Date 1'), ('BOS_2ND_READ', 'Full Board Hearing Date 2'), ('COM_HEARING', 'Committee Hearing Date'), ('MAYORAL_SIGN', 'Mayoral Action - Ordinance Signed Date'), ('TRANSMIT_DATE_BOS', 'Materials Hearing to BOS Clerk Date'), ('COM_HEARING_DATE_BOS', 'Committee Hearing Date - BOS Review')], max_length=50)),
                ('date', models.DateField(verbose_name='Date of hearing.')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppts.Record')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='environment_review',
            field=models.ForeignKey(help_text='Environmental Review type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppts.EnvironmentalReview'),
        ),
        migrations.AddField(
            model_name='record',
            name='mcd_referral',
            field=models.ForeignKey(help_text='Medical Cannabis Dispensary referral', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppts.MCDReferral'),
        ),
    ]
