# Generated by Django 2.2.1 on 2019-05-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppts', '0003_auto_20190510_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.IntegerField(help_text='Primary Key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectdescription',
            name='type',
            field=models.CharField(choices=[('ADDITIONS', 'Additions'), ('ADU', 'Accessory Dwelling Unit'), ('AFFORDABLE_UNITS', '100% Affordable Housing'), ('CHANGE_OF_USE', 'Change of Use'), ('DEMOLITION', 'Demolition'), ('FACADE_ALT', 'Facade Alterations'), ('FINANCIAL', 'Financial Services'), ('FORMULA_RETAIL', 'Formula Retail'), ('INCLUSIONARY', 'Inclusionary Housing Required'), ('LEG_ZONE_CHANGE', 'Legislative/Zoning Change'), ('LOT_LINE_ADJUST', 'Lot Line Adjustment-Subdivision'), ('MASSAGE', 'Massage Establishment'), ('MCD', 'Medical Cannabis Dispensary'), ('NEW_CONSTRUCTION', 'New Construction'), ('OTHER_NON_RES', 'Non-Residential Use Type - Other'), ('OTHER_PRJ_DESC', 'Other'), ('ROW_IMPROVE', 'ROW Improvements'), ('SENIOR', 'Senior Housing'), ('SPECIAL_NEEDS', 'Special Needs Housing'), ('STATE_DENSITY_BONUS', 'State Density Bonus'), ('STUDENT', 'Student Housing'), ('TOBACCO', 'Tobacco Paraphernalia Est')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='record',
            name='parent',
        ),
        migrations.AddField(
            model_name='record',
            name='parent',
            field=models.ManyToManyField(help_text='The parent/child relationship for related records.', related_name='_record_parent_+', to='ppts.Record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='project_description',
            field=models.ManyToManyField(help_text='Checkboxes describing type of project', to='ppts.ProjectDescription'),
        ),
    ]
