# Generated by Django 2.1.7 on 2019-07-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppts', '0004_auto_20190517_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='parent',
            field=models.ManyToManyField(help_text='The parent/child relationship for related records.', related_name='child', to='ppts.Record'),
        ),
    ]
